(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||('id-'+Date.now().toString(36)+Math.random().toString(36).slice(2));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{let d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const monthKey=d=>d.slice(0,7);const addMonths=(s,n)=>{let [y,m]=s.split('-').map(Number);let d=new Date(Date.UTC(y,m-1+n,1));return d.toISOString().slice(0,7)};
function dateOK(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;let [y,m,d]=s.split('-').map(Number);if(y<1900||y>9999)return false;let z=new Date(0);z.setUTCFullYear(y,m-1,d);return z.getUTCFullYear()===y&&z.getUTCMonth()===m-1&&z.getUTCDate()===d}
function cents(v){let s=String(v??'').trim();if(!/^\d{1,9}(?:\.\d{1,2})?$/.test(s))return NaN;let [a,b='']=s.split('.');return Number(a)*100+Number((b+'00').slice(0,2))}
function bp(v){let n=Number(v);return Number.isFinite(n)&&n>=0&&n<=100&&/^\d+(?:\.\d{1,2})?$/.test(String(v))?Math.round(n*100):NaN}
const pct=(x,y)=>y>0?Math.max(0,Math.min(100,Math.round(x/y*100))):0;
const toDate=(y,m,d)=>{let z=new Date(0);z.setUTCFullYear(y,m-1,d);return z.toISOString().slice(0,10)};
function monthDue(m,day){let [y,mo]=m.split('-').map(Number);let last=new Date(Date.UTC(y,mo,0)).getUTCDate();return toDate(y,mo,Math.min(last,Number(day)||1))}
const themes={Ivory:{bg:'#f6f5ee',surface:'#fffefa',surface2:'#e8f2ed',ink:'#173b36',muted:'#526962',line:'#cbd9d1',accent:'#1c6258',accentText:'#fff',peach:'#f4c8b4',chart:'#3a8e7c',danger:'#a2323e',dangerText:'#fff'},Sage:{bg:'#eef3ed',surface:'#fcfefb',surface2:'#ddece2',ink:'#18392e',muted:'#4b6657',line:'#bdd3c3',accent:'#285e45',accentText:'#fff',peach:'#edc6a9',chart:'#367b55',danger:'#a2323e',dangerText:'#fff'},Peach:{bg:'#fff4ed',surface:'#fffdf9',surface2:'#fbe8dc',ink:'#48342d',muted:'#68554b',line:'#e4cdbd',accent:'#775039',accentText:'#fff',peach:'#e9aa89',chart:'#976249',danger:'#9b303a',dangerText:'#fff'},Lilac:{bg:'#f5f2f9',surface:'#fffefe',surface2:'#eae3f1',ink:'#352c44',muted:'#60556d',line:'#d1c6dc',accent:'#614878',accentText:'#fff',peach:'#e9b7ad',chart:'#8561a1',danger:'#9b303a',dangerText:'#fff'},Midnight:{bg:'#101b20',surface:'#1c2b31',surface2:'#263b40',ink:'#f5f8f6',muted:'#d1e0da',line:'#607b7d',accent:'#91e0cb',accentText:'#102623',peach:'#ffc6a8',chart:'#a2e8d4',danger:'#ffb3b4',dangerText:'#301114'}};
const defaults={theme:'Ivory',customThemes:{},accent:'#1c6258',font:'modern',density:'comfortable',card:'rounded',layout:'standard',contrast:false,currency:'USD',customCurrency:'',budget:0,strategy:'snowball',members:['Person 1','Person 2','Shared'],lastBackup:''};
const kinds=['debts','payments','balances','rates','goals','tasks','notes','reviews'];
const state={version:1,settings:structuredClone(defaults),data:Object.fromEntries(kinds.map(k=>[k,[]]))};
const DB=window.DEMO_MODE===true?'harbornest-debt-atlas-demo-v1':'harbornest-debt-atlas-customer-v1';let db,saveQueue=Promise.resolve(),view='dashboard',focusedDebt='',search='',month=today().slice(0,7),calendarMode='month',focusBack,confirmResolve,editing=null,toastTimer,searchTimer;
function openDB(){return new Promise((resolve,reject)=>{let req=indexedDB.open(DB,1);req.onupgradeneeded=()=>req.result.createObjectStore('state');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function loadDB(){return new Promise((resolve,reject)=>{let req=db.transaction('state','readonly').objectStore('state').get('app');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function writeDB(value){return new Promise((resolve,reject)=>{let tx=db.transaction('state','readwrite');tx.objectStore('state').put(value,'app');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function save(){let snapshot=structuredClone(state);saveQueue=saveQueue.catch(()=>{}).then(()=>writeDB(snapshot)).catch(()=>toast('Save failed. Download a backup before closing.'))}
function validImport(s){return s&&s.version===1&&s.settings&&typeof s.settings==='object'&&s.data&&kinds.every(k=>Array.isArray(s.data[k])&&s.data[k].length<50000&&s.data[k].every(r=>r&&typeof r.id==='string'&&Object.values(r).every(v=>typeof v!=='number'||Number.isSafeInteger(v))))}
function money(n){let currency=state.settings.currency==='CUSTOM'?state.settings.customCurrency||'¤':state.settings.currency;let amount=(Number(n)||0)/100;if(state.settings.currency==='CUSTOM')return currency+' '+amount.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});try{return new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:currency==='JPY'?0:2}).format(amount)}catch{return currency+' '+amount.toFixed(2)}}
function stamp(s){return dateOK(s)?new Date(s+'T12:00:00Z').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'—'}
function toast(t){let el=$('[id=toast]');el.textContent=t;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3600)}
function ask(t){focusBack=document.activeElement;$('#confirmText').textContent=t;$('#confirmDialog').showModal();return new Promise(resolve=>confirmResolve=resolve)}
function confirmClose(v){$('#confirmDialog').close();confirmResolve?.(v);confirmResolve=null;focusBack?.focus?.()}
function download(blob,name){let a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)}
function csvCell(v){let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}
function csv(rows,name){download(new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),name)}
function debt(id){return state.data.debts.find(d=>d.id===id)}
function records(kind,id){return state.data[kind].filter(x=>x.debtId===id)}
function latestRate(d,date=today()){let rates=records('rates',d.id).filter(r=>r.date<=date).sort((a,b)=>b.date.localeCompare(a.date));return rates[0]?.rateBp??d.rateBp}
function balanceAt(d,when=today()){let snap=records('balances',d.id).filter(s=>s.date<=when).sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id))[0];let anchor=snap?.balance??d.startingBalance,from=snap?.date||d.startDate||'0000-01-01';let principal=records('payments',d.id).filter(p=>p.date>from&&p.date<=when).reduce((a,p)=>a+p.principal,0);return Math.max(0,anchor-principal)}
const current=d=>balanceAt(d,today());
function active(){return state.data.debts.filter(d=>current(d)>0&&d.status!=='Archived')}
function orderFor(strategy,ds=active()){let rows=[...ds];if(strategy==='avalanche')rows.sort((a,b)=>latestRate(b)-latestRate(a)||current(a)-current(b));else if(strategy==='custom')rows.sort((a,b)=>(a.order??999)-(b.order??999)||a.name.localeCompare(b.name));else rows.sort((a,b)=>current(a)-current(b)||latestRate(b)-latestRate(a));return rows}
function project(opts={}){let rows=orderFor(opts.strategy||state.settings.strategy),budget=opts.budget??state.settings.budget,extra=opts.extra??0,oneTime=opts.oneTime??0,overrideRate=opts.rateBp;let balances=Object.fromEntries(rows.map(d=>[d.id,current(d)])),minTotal=rows.reduce((a,d)=>a+d.minimum,0),series=[],interest=0,spent=0;if(!rows.length)return {ok:true,months:0,interest:0,paid:0,series:[],minTotal};if(budget<minTotal)return {ok:false,reason:'Monthly budget is below your recorded minimum payments.',minTotal};if(budget+extra<=0)return {ok:false,reason:'Enter a positive monthly debt payment budget.',minTotal};for(let n=0;n<600;n++){let m=addMonths(month,n),monthSpent=0,monthInterest=0,remaining=budget+extra+(n===0?oneTime:0),due={};for(let d of rows){let bal=balances[d.id];if(bal<=0)continue;let rate=overrideRate??latestRate(d,monthDue(m,1)),fee=Math.round(bal*rate/120000);balances[d.id]+=fee;interest+=fee;monthInterest+=fee;let pay=Math.min(balances[d.id],d.minimum);due[d.id]=pay;remaining-=pay}if(remaining<0)return {ok:false,reason:'Entered budget does not cover minimum payments and projected interest.',minTotal};for(let d of rows){let pay=due[d.id]||0;balances[d.id]=Math.max(0,balances[d.id]-pay);monthSpent+=pay}for(let d of rows){if(remaining<=0)break;let pay=Math.min(remaining,balances[d.id]);balances[d.id]-=pay;remaining-=pay;monthSpent+=pay}spent+=monthSpent;let total=Object.values(balances).reduce((a,b)=>a+b,0);series.push({month:m,total,paid:monthSpent,interest:monthInterest});if(total<=0)return {ok:true,months:n+1,interest,paid:spent,series,minTotal,date:monthDue(m,1)};if(n>=11&&series[n].total>=series[n-11].total)return {ok:false,reason:'Payments do not reduce the projected balance. Increase the budget or review interest rates.',minTotal,series}}return {ok:false,reason:'Projection exceeds 50 years; increase payments to calculate a useful date.',minTotal,series}}
function summary(){let ds=state.data.debts,original=ds.reduce((a,d)=>a+d.startingBalance,0),remaining=ds.reduce((a,d)=>a+current(d),0),payments=state.data.payments,totalPaid=payments.reduce((a,p)=>a+p.amount+p.extra,0),extra=payments.reduce((a,p)=>a+p.extra,0),min=active().reduce((a,d)=>a+d.minimum,0);return {original,remaining,paidDown:original-remaining,payments:totalPaid,extra,min,count:ds.length,paidOff:ds.filter(d=>current(d)===0).length,rate:Math.max(0,...ds.map(d=>latestRate(d))),projection:project()}}
const F=(key,label,type='text',required=false,choices='')=>({key,label,type,required,choices});
const defs={
 debts:{label:'Debts & accounts',fields:[F('name','Debt name','text',true),F('type','Debt type','select',true,'Credit card|Personal loan|Auto loan|Student loan|Mortgage|Medical debt|Buy now pay later|Family loan|Tax debt|Other'),F('creditor','Institution / creditor'),F('owner','Owner','select',false,'Person 1|Person 2|Shared|Household|Other'),F('startingBalance','Opening recorded balance','money',true),F('rateBp','Annual interest rate (%)','rate',true),F('minimum','Monthly minimum payment','money',true),F('dueDay','Due day (1–31)','number',true),F('startDate','Balance record date','date',true),F('targetDate','Personal target date','date'),F('priority','Priority','select',false,'High|Medium|Low'),F('status','Status','select',false,'Active|Paused|Archived'),F('notes','Notes','textarea')]},
 payments:{label:'Payment history',fields:[F('debtId','Debt','debt',true),F('date','Payment date','date',true),F('amount','Regular / scheduled paid amount','money',true),F('extra','Additional paid amount','money'),F('interest','Interest portion recorded','money'),F('principal','Principal portion applied','money'),F('method','Payment method / reference'),F('notes','Notes','textarea')]},
 balances:{label:'Balance snapshots',fields:[F('debtId','Debt','debt',true),F('date','Statement date','date',true),F('balance','Recorded balance','money',true),F('notes','Notes','textarea')]},
 rates:{label:'Rate changes',fields:[F('debtId','Debt','debt',true),F('date','Effective date','date',true),F('rateBp','New annual rate (%)','rate',true),F('notes','Notes','textarea')]},
 goals:{label:'Financial goals',fields:[F('name','Goal name','text',true),F('type','Goal type','select',true,'Total balance below|Extra payments at least|Pay off a debt|Payoff percent at least|Custom progress'),F('debtId','Related debt','optionalDebt'),F('target','Target amount or percent','money'),F('current','Custom progress amount','money'),F('targetDate','Target date','date'),F('status','Status','select',false,'Active|Completed|Paused'),F('notes','Notes','textarea')]},
 tasks:{label:'Tasks & reminders',fields:[F('name','Task / in-app reminder','text',true),F('debtId','Related debt','optionalDebt'),F('date','Due date','date',true),F('priority','Priority','select',false,'High|Medium|Low'),F('status','Status','select',false,'To do|Done'),F('notes','Notes','textarea')]},
 notes:{label:'Notes',fields:[F('name','Title','text',true),F('debtId','Related debt','optionalDebt'),F('date','Date','date',true),F('notes','Details','textarea',true)]},
 reviews:{label:'Monthly & yearly reviews',fields:[F('name','Review title','text',true),F('period','Period','select',true,'Monthly|Yearly'),F('date','Period end date','date',true),F('changed','What changed?','textarea'),F('worked','What worked well?','textarea'),F('adjust','What to adjust?','textarea')]}
};
const groups=[['OVERVIEW',[['dashboard','Dashboard','◉'],['debts','Debts & accounts','▤'],['payments','Payments','▣']]],['PLAN',[['strategies','Strategies','✧'],['calculator','Calculator & what-if','∑'],['schedule','Calendar & due dates','▦']]],['GROW',[['progress','Progress & charts','◌'],['goals','Goals & milestones','◎'],['reviews','Reviews & reports','▥']]],['ORGANIZE',[['tasks','Tasks & reminders','☑'],['notes','Notes','☷'],['settings','Customize & backup','⚙']]]];
const pageLabels=Object.fromEntries(groups.flatMap(([,links])=>links.map(([k,l])=>[k,l])));
function nav(){let h='';for(let [g,links] of groups){h+=`<div class="navgroup">${g}</div>`;for(let [key,label,icon] of links)h+=`<button class="navitem ${view===key?'active':''}" data-nav="${key}"><span class="navicon">${icon}</span>${esc(label)}</button>`}$('#nav').innerHTML=h;$('#mobileNav').innerHTML=[['dashboard','Home','◉'],['debts','Debts','▤'],['payments','Payments','▣'],['schedule','Dates','▦'],['settings','Settings','⚙']].map(([k,l,i])=>`<button data-nav="${k}" class="${view===k?'active':''}"><b>${i}</b>${l}</button>`).join('')}
function applyAppearance(){let s=state.settings,t=themes[s.theme]||s.customThemes[s.theme]||themes.Ivory,root=document.documentElement;for(let k of ['bg','surface','surface2','ink','muted','line','accent','accentText','peach','chart','danger','dangerText'])root.style.setProperty('--'+k,t[k]);document.body.dataset.theme=s.theme;for(let k of ['font','density','card','layout','contrast'])document.body.dataset[k]=s[k];document.querySelector('meta[name="theme-color"]').content=t.accent;}
function navigate(k){view=k;search='';focusedDebt=k==='debts'?focusedDebt:'';nav();$('#pageTitle').textContent=pageLabels[k]||'Planner';renderView();$('.sidebar').classList.remove('open');$('#menuBtn').setAttribute('aria-expanded','false');window.scrollTo(0,0)}
function stat(cards){return `<div class="stats">${cards.map(([label,val,hint])=>`<div class="stat"><span class="label">${esc(label)}</span><strong class="mono">${esc(val)}</strong><span class="hint">${esc(hint||'')}</span></div>`).join('')}</div>`}
function bar(x,y){return `<div class="progress" role="progressbar" aria-valuenow="${pct(x,y)}" aria-valuemin="0" aria-valuemax="100"><i style="width:${pct(x,y)}%"></i></div>`}
function title(k,sub,buttons=''){return `<div class="sectionhead"><div><small class="eyebrow">${esc(k.toUpperCase())}</small><h1>${esc(pageLabels[view]||k)}</h1><p>${esc(sub)}</p></div><div class="toolbar">${buttons}</div></div>`}
function donut(n){return `<div class="donut" style="--pct:${n}%"><span>${n}%</span></div>`}
function lineChart(points,labels=[]){if(!points.length)return '<div class="empty">Add records to build your trend.</div>';let values=points.map(Number),max=Math.max(...values,1),min=Math.min(...values,0),range=Math.max(1,max-min),xy=values.map((v,i)=>[24+i*752/Math.max(1,values.length-1),210-(v-min)/range*170]);let path=xy.map(([x,y],i)=>(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)).join(' ');return `<svg class="chart" viewBox="0 0 800 250" role="img" aria-label="Trend chart: ${esc(labels.join(', '))}"><path d="M24 220H776" fill="none" stroke="var(--line)" stroke-width="2"/><path d="${path}" fill="none" stroke="var(--chart)" stroke-width="4" stroke-linejoin="round" stroke-linecap="round"/>${xy.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="5" fill="var(--accent)"><title>${esc(labels[i]||'Entry '+(i+1))}: ${esc(money(values[i]))}</title></circle>`).join('')}</svg>`}
function dashboard(){let s=summary(),p=s.projection,up=upcoming().slice(0,4),goals=state.data.goals.filter(g=>g.status==='Active');if(!s.count)return `<section class="hero"><div><small class="eyebrow">WELCOME TO DEBT ATLAS</small><h1>Start with one account.</h1><p>Add a debt balance, rate and monthly minimum. Your plan will grow one clear step at a time.</p><button class="primary" data-add="debts">+ Add your first debt</button></div><div class="hero-aside"><span>Private by design</span><strong>No bank connection</strong><span>Records stay in this browser.</span></div></section><div class="grid"><div class="panel"><h2>Your first three steps</h2><p>1. Add a debt. 2. Set your monthly budget. 3. Review a payoff strategy.</p></div><div class="panel"><h2>Bring existing records</h2><p>Open Customize & backup to restore a JSON backup from another device.</p><button class="quiet" data-nav="settings">Open settings</button></div></div>`;
let extraMonth=state.data.payments.filter(x=>monthKey(x.date)===month).reduce((a,x)=>a+x.extra,0);return `<section class="hero"><div><small class="eyebrow">YOUR DEBT COMMAND CENTER</small><h1>Progress, one payment at a time.</h1><p>${s.count} accounts recorded · ${active().length} with balances · ${s.paidOff} paid off</p><button class="primary" data-add="payments">+ Record a payment</button> <button class="quiet" data-nav="strategies">View payoff plan</button></div><div class="hero-aside"><span>Estimated debt-free date</span><strong>${p.ok?stamp(p.date):'Not available yet'}</strong><span>${p.ok?p.months+' months under entered assumptions':p.reason}</span></div></section>`+
stat([['Current recorded debt',money(s.remaining),'From balances and principal records'],['Total paid down',money(s.paidDown),'Original minus current recorded debt'],['Minimums per month',money(s.min),'Across active debts'],['Extra paid this month',money(extraMonth),'Recorded additional payments']])+`<div class="cols"><div class="panel"><h2>Debt-free progress</h2>${donut(pct(s.paidDown,s.original))}<p class="muted">${money(s.remaining)} remaining of ${money(s.original)} originally recorded.</p>${bar(s.paidDown,s.original)}</div><div class="panel"><div class="panelhead"><h2>Next due</h2><button class="smallbtn" data-nav="schedule">See calendar</button></div>${up.length?up.map(x=>`<div class="record"><div><h3>${esc(x.debt.name)}</h3><div class="meta">${stamp(x.date)} · ${money(x.debt.minimum)}</div></div><span class="pill ${x.status==='Overdue'?'bad':x.status==='Due today'?'warn':''}">${esc(x.status)}</span></div>`).join(''):'<div class="empty">No upcoming debt payments.</div>'}</div></div><div class="cols" style="margin-top:18px"><div class="panel"><h2>At a glance</h2>${active().slice(0,6).map(d=>`<div class="barrow"><span>${esc(d.name)}</span>${bar(d.startingBalance-current(d),d.startingBalance)}<b>${pct(d.startingBalance-current(d),d.startingBalance)}%</b></div>`).join('')}</div><div class="panel"><h2>Focus on the next step</h2><p>${goals.length?esc(goals[0].name):'Add a goal to make the next milestone visible.'}</p><p class="muted">${p.ok?`At ${money(state.settings.budget)} monthly, the mathematical estimate is ${p.months} months.`:'Set a budget that covers your minimum payments to get a projection.'}</p><button class="quiet" data-nav="goals">Goals & milestones</button></div></div>`}
function recordActions(k,r){return `<div class="record-actions"><button class="smallbtn" data-edit="${k}" data-id="${esc(r.id)}" aria-label="Edit ${esc(r.name||k)}">Edit</button><button class="smallbtn" data-delete="${k}" data-id="${esc(r.id)}" aria-label="Delete ${esc(r.name||k)}">Delete</button></div>`}
function debtCard(d){let b=current(d),paid=d.startingBalance-b;return `<article class="record"><div><small class="eyebrow">${esc(d.type)} · ${esc(d.owner||'Individual')}</small><h3>${esc(d.name)}</h3><div class="meta">${esc(d.creditor||'No creditor entered')} · ${esc((latestRate(d)/100).toFixed(2))}% APR · Due day ${d.dueDay}</div><p><strong>${money(b)}</strong> recorded balance · ${money(d.minimum)} minimum</p><div style="max-width:360px">${bar(paid,d.startingBalance)}</div></div><div class="record-actions"><button class="smallbtn" data-detail="${esc(d.id)}">Open account</button>${recordActions('debts',d)}</div></article>`}
function debtDetail(d){let pays=records('payments',d.id).sort((a,b)=>b.date.localeCompare(a.date)),b=current(d),p=project({strategy:'custom'}),rate=latestRate(d);return `${title('Account workspace','Balance, payments and dated rate records for this account.',`<button class="quiet" data-back="debts">← All debts</button><button class="primary" data-add="payments" data-debt="${esc(d.id)}">+ Payment</button>`)}<section class="hero"><div><small class="eyebrow">${esc(d.type)} · ${esc(d.owner||'Individual')}</small><h1>${esc(d.name)}</h1><p>${esc(d.creditor||'')} · ${esc(d.notes||'No notes yet.')}</p></div><div class="hero-aside"><span>Current recorded balance</span><strong>${money(b)}</strong><span>${pct(d.startingBalance-b,d.startingBalance)}% paid down</span></div></section>${stat([['Opening balance',money(d.startingBalance)],['Recorded principal',money(pays.reduce((a,x)=>a+x.principal,0))],['Current APR',`${(rate/100).toFixed(2)}%`],['Minimum / due day',money(d.minimum),`Day ${d.dueDay}`]])}<div class="grid"><div class="panel"><h2>Account actions</h2><div class="toolbar"><button class="quiet" data-add="balances" data-debt="${esc(d.id)}">Record balance snapshot</button><button class="quiet" data-add="rates" data-debt="${esc(d.id)}">Record rate change</button><button class="quiet" data-edit="debts" data-id="${esc(d.id)}">Edit debt</button></div><p class="muted">Statement snapshots reconcile the current balance. Later principal payments reduce it.</p></div><div class="panel"><h2>Payment history</h2>${pays.length?pays.slice(0,8).map(x=>`<div class="record"><div><b>${money(x.amount+x.extra)}</b><div class="meta">${stamp(x.date)} · Principal ${money(x.principal)} · Interest ${money(x.interest)}</div></div>${recordActions('payments',x)}</div>`).join(''):'<div class="empty">No payments recorded yet.</div>'}</div></div><div class="cols" style="margin-top:18px"><div class="panel"><h2>Balance snapshots</h2>${records('balances',d.id).sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="record"><div><b>${money(x.balance)}</b><div class="meta">${stamp(x.date)}</div></div>${recordActions('balances',x)}</div>`).join('')||'<div class="empty">No statement balances yet.</div>'}</div><div class="panel"><h2>Rate history</h2>${records('rates',d.id).sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="record"><div><b>${(x.rateBp/100).toFixed(2)}% APR</b><div class="meta">Effective ${stamp(x.date)}</div></div>${recordActions('rates',x)}</div>`).join('')||'<div class="empty">No rate changes recorded.</div>'}</div></div>`}
function debtView(){if(focusedDebt){let d=debt(focusedDebt);if(d)return debtDetail(d);focusedDebt=''}let ds=state.data.debts.filter(d=>!search||[d.name,d.creditor,d.type,d.owner].some(x=>String(x||'').toLowerCase().includes(search.toLowerCase())));return `${title('Accounts','Credit cards, loans and other balances in one private workspace.',`<button class="primary" data-add="debts">+ Add debt</button>`)}<div class="toolbar"><input id="listSearch" type="search" value="${esc(search)}" placeholder="Search name, creditor, type or owner" aria-label="Search debts"></div><div id="listContainer">${ds.length?ds.map(debtCard).join(''):'<div class="empty"><h3>No matching debts</h3><p>Add an account or change the search.</p></div>'}</div>`}
function paymentView(){let rows=state.data.payments.filter(p=>{let d=debt(p.debtId);return !search||[d?.name,p.date,p.method,p.notes,String((p.amount+p.extra)/100)].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase()))}).sort((a,b)=>b.date.localeCompare(a.date));let sum=rows.reduce((a,p)=>a+p.amount+p.extra,0),interest=rows.reduce((a,p)=>a+p.interest,0);return `${title('History','Record regular, partial and extra payments. Principal updates the balance.',`<button class="primary" data-add="payments">+ Record payment</button><button class="quiet" data-csv="payments">Export CSV</button>`)}${stat([['Payments recorded',rows.length],['Total paid',money(sum)],['Extra paid',money(rows.reduce((a,p)=>a+p.extra,0))],['Interest recorded',money(interest)]])}<div class="toolbar"><input id="listSearch" type="search" value="${esc(search)}" placeholder="Search debt, date, method or amount" aria-label="Search payments"></div><div id="listContainer">${rows.length?rows.map(p=>`<article class="record"><div><h3>${esc(debt(p.debtId)?.name||'Removed debt')}</h3><div class="meta">${stamp(p.date)} · ${esc(p.method||'No method')} · Principal ${money(p.principal)} · Interest ${money(p.interest)}</div><p>Regular ${money(p.amount)} · Extra ${money(p.extra)}</p></div><div><b>${money(p.amount+p.extra)}</b>${recordActions('payments',p)}</div></article>`).join(''):'<div class="empty">No payments recorded.</div>'}</div>`}

function upcoming(){let out=[];for(let d of active())for(let m of [addMonths(month,-1),month,addMonths(month,1)]){let date=monthDue(m,d.dueDay),paid=records('payments',d.id).filter(p=>monthKey(p.date)===m).reduce((a,p)=>a+p.amount+p.extra,0),status=paid>=d.minimum?'Paid':paid?'Partial':date<today()?'Overdue':'Upcoming';out.push({debt:d,date,status,paid})}return out.sort((a,b)=>a.date.localeCompare(b.date))}
function listRows(kind){return state.data[kind].filter(r=>!search||JSON.stringify(r).toLowerCase().includes(search.toLowerCase())).map(r=>'<article class="record"><div><h3>'+esc(r.name||debt(r.debtId)?.name||kind)+'</h3><div class="meta">'+esc(r.date||r.targetDate||'')+' · '+esc(r.type||r.status||r.period||'')+'</div><p>'+esc(r.notes||r.changed||'')+'</p></div>'+recordActions(kind,r)+'</article>').join('')||'<div class="empty">No records yet.</div>'}
function genericView(kind,sub){return title(defs[kind].label,sub,'<button class="primary" data-add="'+kind+'">+ Add record</button>')+'<div class="toolbar"><input id="listSearch" type="search" value="'+esc(search)+'" placeholder="Search records" aria-label="Search records"></div><div id="listContainer" class="panel">'+listRows(kind)+'</div>'}
function strategiesView(){let p=project(),s=summary(),h=title('Payoff strategies','Snowball, avalanche or custom account order.');h+='<div class="panel"><div class="form-grid"><label>Method<select id="strategyChoice">'+['snowball','avalanche','custom'].map(x=>'<option value="'+x+'" '+(state.settings.strategy===x?'selected':'')+'>'+x+'</option>').join('')+'</select></label><label>Monthly debt budget<input id="budgetInput" type="number" min="0" step=".01" value="'+(state.settings.budget/100).toFixed(2)+'"></label></div><p>Recorded minimums: '+money(s.min)+'</p></div>';h+=p.ok?stat([['Estimated payoff',stamp(p.date)],['Projected interest',money(p.interest)],['Duration',p.months+' months']]):'<div class="notice">'+esc(p.reason)+'</div>';h+='<div class="panel"><h2>Payoff priority</h2>'+orderFor(state.settings.strategy).map((d,i)=>'<div class="record"><div><b>'+(i+1)+'. '+esc(d.name)+'</b><p>'+money(current(d))+' · '+(latestRate(d)/100).toFixed(2)+'% APR</p></div><div><button class="smallbtn" data-move="'+esc(d.id)+'" data-dir="-1">↑</button> <button class="smallbtn" data-move="'+esc(d.id)+'" data-dir="1">↓</button></div></div>').join('')+'</div><p class="disclaimer">Mathematical estimate from entered balances, rates and a fixed monthly budget. Actual lender schedules may differ.</p>';return h}
function calculatorView(){return title('What-if calculator','Explore a scenario without changing your records.')+'<div class="cols"><div class="panel"><h2>Scenario inputs</h2><div class="form-grid"><label>Monthly budget<input id="simBudget" type="number" min="0" step=".01" value="'+(state.settings.budget/100).toFixed(2)+'"></label><label>Extra monthly<input id="simExtra" type="number" min="0" step=".01" value="0"></label><label>One-time payment<input id="simOne" type="number" min="0" step=".01" value="0"></label><label>Method<select id="simStrategy"><option value="snowball">Snowball</option><option value="avalanche">Avalanche</option><option value="custom">Custom</option></select></label></div><button class="primary" id="runScenario">Calculate</button></div><div class="panel" id="scenarioResult"><h2>Scenario result</h2><p>Enter your assumptions and calculate.</p></div></div>'}
function scheduleView(){let all=upcoming().filter(x=>monthKey(x.date)===month),[y,m]=month.split('-').map(Number),first=new Date(Date.UTC(y,m-1,1)).getUTCDay(),days=new Date(Date.UTC(y,m,0)).getUTCDate(),cells=Array.from({length:first},()=>'<div class="cal-day blank"></div>');for(let d=1;d<=days;d++){let day=toDate(y,m,d),events=all.filter(x=>x.date===day);cells.push('<div class="cal-day '+(day===today()?'today':'')+'"><b>'+d+'</b>'+events.map(x=>'<button class="cal-event" data-detail="'+esc(x.debt.id)+'">'+esc(x.debt.name)+'<small>'+esc(x.status)+'</small></button>').join('')+'</div>')}return title('Due date calendar','Dates and statuses are based on your records.','<button class="primary" data-add="tasks">+ Reminder</button>')+'<div class="panel"><div class="panelhead"><h2>'+new Date(Date.UTC(y,m-1,1)).toLocaleString(undefined,{month:'long',year:'numeric',timeZone:'UTC'})+'</h2><div><button class="smallbtn" data-month="-1">←</button> <button class="smallbtn" data-month="1">→</button></div></div><div class="calendar">'+['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>'<div class="weekday">'+x+'</div>').join('')+cells.join('')+'</div></div><div class="panel"><h2>Due this month</h2>'+all.map(x=>'<div class="record"><div><b>'+esc(x.debt.name)+'</b><p>'+stamp(x.date)+' · '+money(x.debt.minimum)+'</p></div><span class="pill">'+esc(x.status)+'</span></div>').join('')+'</div><p class="disclaimer">Reminders appear only while this planner is open.</p>'}
function progressView(){let s=summary(),p=s.projection,months=[...new Set(state.data.payments.map(x=>monthKey(x.date)))].sort().slice(-12),amounts=months.map(m=>state.data.payments.filter(x=>monthKey(x.date)===m).reduce((a,x)=>a+x.amount+x.extra,0));return title('Progress & charts','Automatically calculated from your records.','<button class="quiet" data-print="1">Print</button>')+stat([['Accounts paid off',s.paidOff],['Paid down',money(s.paidDown)],['Recorded payments',money(s.payments)],['Estimated date',p.ok?stamp(p.date):'Not available']])+'<div class="cols"><div class="panel"><h2>Payoff progress</h2>'+donut(pct(s.paidDown,s.original))+'</div><div class="panel"><h2>Payments by month</h2>'+lineChart(amounts,months)+'</div></div><div class="panel"><h2>Account progress</h2>'+state.data.debts.map(d=>'<div class="barrow"><span>'+esc(d.name)+'</span>'+bar(d.startingBalance-current(d),d.startingBalance)+'<b>'+pct(d.startingBalance-current(d),d.startingBalance)+'%</b></div>').join('')+'</div>'}
function goalsView(){let s=summary();return title('Goals & milestones','Make each bit of progress visible.','<button class="primary" data-add="goals">+ Goal</button>')+'<div class="panel"><h2>Payoff milestones</h2><div class="milestones">'+[10,25,50,75,90,100].map(n=>'<div class="milestone '+(pct(s.paidDown,s.original)>=n?'earned':'')+'"><b>'+n+'%</b><span>'+(pct(s.paidDown,s.original)>=n?'Reached':'Ahead')+'</span></div>').join('')+'</div></div><div class="panel"><h2>Personal goals</h2>'+listRows('goals')+'</div>'}
function reviewsView(){let s=summary(),rows=state.data.payments.filter(x=>monthKey(x.date)===month);return title('Reviews & reports','Monthly and yearly reflections.','<button class="primary" data-add="reviews">+ Review</button><button class="quiet" data-print="1">Print</button><button class="quiet" data-csv="summary">Export CSV</button>')+stat([['This month paid',money(rows.reduce((a,p)=>a+p.amount+p.extra,0))],['This month extra',money(rows.reduce((a,p)=>a+p.extra,0))],['Remaining',money(s.remaining)],['Paid off',s.paidOff]])+'<div class="panel"><h2>Saved reviews</h2>'+listRows('reviews')+'</div>'}
function settingsView(){let s=state.settings;return title('Customize & backup','Your display, your records.')+'<div class="cols"><div class="panel"><h2>Color themes</h2><div class="theme-grid">'+Object.entries({...themes,...s.customThemes}).map(([name,t])=>'<button class="theme-tile '+(s.theme===name?'selected':'')+'" data-theme-choice="'+esc(name)+'" aria-pressed="'+(s.theme===name)+'"><i style="background:'+esc(t.bg)+';border-color:'+esc(t.accent)+'"><b style="background:'+esc(t.accent)+'"></b></i><span>'+esc(name)+'</span></button>').join('')+'</div><label>Accent color<input id="customAccent" type="color" value="'+esc(s.accent)+'"></label><button class="quiet" id="saveCustomTheme">Save custom theme</button></div><div class="panel"><h2>Display</h2><div class="form-grid">'+[['currency',['USD','GBP','EUR','CAD','AUD','INR','PKR','JPY','CUSTOM']],['font',['modern','editorial']],['density',['comfortable','compact']],['card',['rounded','square']],['layout',['standard','wide']]].map(([key,opts])=>'<label>'+key+'<select data-setting="'+key+'">'+opts.map(x=>'<option value="'+x+'" '+(s[key]===x?'selected':'')+'>'+x+'</option>').join('')+'</select></label>').join('')+'<label>Custom currency<input data-setting="customCurrency" maxlength="4" value="'+esc(s.customCurrency)+'"></label></div><label class="check"><input type="checkbox" data-setting="contrast" '+(s.contrast?'checked':'')+'> Extra contrast</label></div></div><div class="cols"><div class="panel"><h2>Monthly budget</h2><label>Debt payment budget<input id="settingsBudget" type="number" min="0" step=".01" value="'+(s.budget/100).toFixed(2)+'"></label></div><div class="panel"><h2>Backup & privacy</h2><p>Data is saved to this browser. Backup before clearing browser data or changing devices.</p><div class="toolbar"><button class="quiet" id="backupBtn">Download JSON</button><button class="quiet" id="restoreBtn">Restore JSON</button><button class="quiet" data-csv="debts">Debts CSV</button><button class="danger" id="resetBtn">Erase local data</button></div></div></div>'}
function renderView(){let fn={dashboard,debts:debtView,payments:paymentView,strategies:strategiesView,calculator:calculatorView,schedule:scheduleView,progress:progressView,goals:goalsView,reviews:reviewsView,tasks:()=>genericView('tasks','Payment follow-ups and actions.'),notes:()=>genericView('notes','Keep context for decisions.'),settings:settingsView}[view]||dashboard;$('#view').innerHTML=fn()}

function fieldHTML(f,v){let val=v?.[f.key]??'',type=f.type;if(type==='money')val=(Number(val)/100||0).toFixed(2);if(type==='rate')val=(Number(val)/100||0).toFixed(2);let id='field-'+f.key,label='<label for="'+id+'">'+esc(f.label)+(f.required?' *':'')+'</label>',attr=' id="'+id+'" name="'+f.key+'" '+(f.required?'required ':'');if(type==='textarea')return '<div class="field wide">'+label+'<textarea'+attr+' rows="3">'+esc(val)+'</textarea></div>';if(type==='select'||type==='debt'||type==='optionalDebt'){let options=type==='select'?f.choices.split('|').map(x=>[x,x]):state.data.debts.map(d=>[d.id,d.name]);return '<div class="field">'+label+'<select'+attr+'><option value="">Select…</option>'+options.map(([x,y])=>'<option value="'+esc(x)+'" '+(val===x?'selected':'')+'>'+esc(y)+'</option>').join('')+'</select></div>'}let inputType=type==='money'||type==='rate'||type==='number'?'number':type;return '<div class="field">'+label+'<input'+attr+' type="'+inputType+'" value="'+esc(val)+'" '+(inputType==='number'?'min="0" step="'+(type==='number'?'1':'.01')+'"':'')+'></div>'}
function openForm(kind,id='',pref=''){let record=state.data[kind]?.find(x=>x.id===id),schema=defs[kind];if(!schema)return;editing={kind,id};focusBack=document.activeElement;$('#editorTitle').textContent=(record?'Edit ':'Add ')+schema.label;$('#editorEyebrow').textContent=kind.toUpperCase();$('#formFields').innerHTML=schema.fields.map(f=>fieldHTML(f,record||{debtId:pref,date:today(),startDate:today(),status:kind==='debts'?'Active':kind==='tasks'?'To do':'Active',priority:'Medium',period:'Monthly',dueDay:1})).join('');$('#formError').hidden=true;$('#editor').showModal();$('#formFields input,#formFields select')?.focus()}
function closeEditor(){if($('#editor').open)$('#editor').close();focusBack?.focus?.()}
function submitForm(e){e.preventDefault();let {kind,id}=editing,raw=Object.fromEntries(new FormData(e.currentTarget)),out={id:id||uid()},err='';for(let f of defs[kind].fields){let v=String(raw[f.key]??'').trim();if(f.required&&!v){err=f.label+' is required.';break}if(f.type==='date'&&v&&!dateOK(v)){err=f.label+' needs a real YYYY-MM-DD date.';break}if(f.type==='money'){let n=v?cents(v):0;if(!Number.isSafeInteger(n)){err=f.label+' must be a valid nonnegative amount with at most two decimals.';break}out[f.key]=n}else if(f.type==='rate'){let n=bp(v||'0');if(!Number.isSafeInteger(n)){err=f.label+' must be between 0 and 100%.';break}out[f.key]=n}else if(f.type==='number'){let n=Number(v);if(!Number.isSafeInteger(n)||n<1||n>31){err=f.label+' must be a day from 1 to 31.';break}out[f.key]=n}else out[f.key]=v.slice(0,f.type==='textarea'?4000:200)}if(!err&&kind==='payments'){let total=out.amount+out.extra;if(!total)err='Enter a payment above zero.';if(out.interest>total)err='Interest cannot exceed the payment.';if(!out.principal)out.principal=Math.max(0,total-out.interest);if(out.principal+out.interest>total)err='Principal plus interest exceeds total paid.'}if(!err&&kind==='debts'&&out.minimum>out.startingBalance&&out.startingBalance>0)err='Minimum payment exceeds opening balance.';if(!err&&out.debtId&&!debt(out.debtId))err='Choose an existing debt.';if(err){$('#formError').textContent=err;$('#formError').hidden=false;return}let a=state.data[kind],i=a.findIndex(x=>x.id===id);if(i>=0)a[i]=out;else a.push(out);save();closeEditor();renderView();toast('Saved '+defs[kind].label.toLowerCase()+'.')}
function exportCSV(kind){let rows;if(kind==='summary'){let s=summary(),p=s.projection;rows=[['Metric','Value'],['Current balance',(s.remaining/100).toFixed(2)],['Paid down',(s.paidDown/100).toFixed(2)],['Estimated payoff',p.ok?p.date:'Not available'],['Projection note',p.ok?'Monthly estimate':p.reason]]}else if(kind==='debts')rows=[['Name','Type','Creditor','Owner','Opening Balance','Current Balance','APR %','Minimum','Due Day','Start Date','Target Date','Status','Notes'],...state.data.debts.map(d=>[d.name,d.type,d.creditor,d.owner,(d.startingBalance/100).toFixed(2),(current(d)/100).toFixed(2),(latestRate(d)/100).toFixed(2),(d.minimum/100).toFixed(2),d.dueDay,d.startDate,d.targetDate,d.status,d.notes])];else rows=[['Debt','Date','Regular','Extra','Principal','Interest','Method','Notes'],...state.data.payments.map(p=>[debt(p.debtId)?.name||'',p.date,(p.amount/100).toFixed(2),(p.extra/100).toFixed(2),(p.principal/100).toFixed(2),(p.interest/100).toFixed(2),p.method,p.notes])];csv(rows,'HarborNest-Debt-Atlas-'+kind+'.csv')}
function demoSeed(){let ds=[['Evergreen Card',420000,1899,12500,12],['Studio Loan',850000,785,18500,20],['New Horizons Card',185000,2499,8500,6]].map(([name,startingBalance,rateBp,minimum,dueDay],i)=>({id:'sample-debt-'+i,name,type:i===1?'Personal loan':'Credit card',creditor:'Sample lender',owner:'Person 1',startingBalance,rateBp,minimum,dueDay,startDate:addMonths(today().slice(0,7),-3)+'-01',targetDate:'',priority:'Medium',status:'Active',notes:'Fictional demo record.',order:i}));state.data.debts=ds;state.settings.budget=58000;state.data.payments=[{id:'sample-payment',debtId:ds[0].id,date:addMonths(today().slice(0,7),-1)+'-12',amount:12500,extra:7500,interest:6500,principal:13500,method:'Manual transfer',notes:'Fictional payment'}];state.data.goals=[{id:'sample-goal',name:'First card below $3,000',type:'Total balance below',debtId:ds[0].id,target:300000,current:0,targetDate:'',status:'Active',notes:''}];state.data.tasks=[{id:'sample-task',name:'Review next statement',debtId:ds[0].id,date:monthDue(month,12),priority:'Medium',status:'To do',notes:''}]}
function handleClick(e){let b=e.target.closest('button');if(!b)return;if(b.dataset.nav)return navigate(b.dataset.nav);if(b.dataset.add)return openForm(b.dataset.add,'',b.dataset.debt||'');if(b.dataset.edit)return openForm(b.dataset.edit,b.dataset.id);if(b.dataset.detail){focusedDebt=b.dataset.detail;return navigate('debts')}if(b.dataset.back){focusedDebt='';return navigate(b.dataset.back)}if(b.dataset.month){month=addMonths(month,Number(b.dataset.month));return renderView()}if(b.dataset.themeChoice){state.settings.theme=b.dataset.themeChoice;applyAppearance();save();return renderView()}if(b.dataset.csv)return exportCSV(b.dataset.csv);if(b.dataset.print)return window.print();if(b.dataset.delete){let kind=b.dataset.delete,id=b.dataset.id;ask('Delete this record? This cannot be undone.').then(ok=>{if(!ok)return;if(kind==='debts'&&['payments','balances','rates'].some(k=>records(k,id).length)){toast('Delete linked payments, balances and rates first.');return}state.data[kind]=state.data[kind].filter(x=>x.id!==id);save();renderView();toast('Record deleted.')});return}if(b.dataset.move){let a=orderFor('custom'),i=a.findIndex(x=>x.id===b.dataset.move),j=i+Number(b.dataset.dir);if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];a.forEach((d,n)=>d.order=n);state.settings.strategy='custom';save();return renderView()}if(b.id==='runScenario'){let budget=cents($('#simBudget').value),extra=cents($('#simExtra').value),oneTime=cents($('#simOne').value);if([budget,extra,oneTime].some(x=>!Number.isSafeInteger(x))){$('#scenarioResult').textContent='Use valid nonnegative amounts.';return}let p=project({budget,extra,oneTime,strategy:$('#simStrategy').value});$('#scenarioResult').innerHTML='<h2>Scenario result</h2><p>'+(p.ok?'Estimated payoff: '+stamp(p.date)+' · '+p.months+' months · interest '+money(p.interest):esc(p.reason))+'</p>';return}if(b.id==='saveCustomTheme'){let hex=$('#customAccent').value,base=themes.Ivory;let rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255),l=rgb.map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4),lum=.2126*l[0]+.7152*l[1]+.0722*l[2],accentText=lum>.179?'#102623':'#ffffff';let name='Custom '+(Object.keys(state.settings.customThemes).length+1);state.settings.customThemes[name]={...base,accent:hex,accentText,chart:hex};state.settings.theme=name;state.settings.accent=hex;save();applyAppearance();renderView();toast(name+' saved.');return}if(b.id==='backupBtn'){state.settings.lastBackup=today();save();download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'HarborNest-Debt-Atlas-backup-'+today()+'.json');return}if(b.id==='restoreBtn')return $('#restoreFile').click();if(b.id==='resetBtn'){ask('Permanently erase all local planner records? Download a backup first if you need them.').then(ok=>{if(!ok)return;state.data=Object.fromEntries(kinds.map(k=>[k,[]]));state.settings=structuredClone(defaults);if(window.DEMO_MODE)demoSeed();save();applyAppearance();navigate('dashboard');toast('Planner reset.')});return}}
function handleChange(e){let t=e.target;if(t.id==='strategyChoice'){state.settings.strategy=t.value;save();renderView()}else if(t.id==='budgetInput'||t.id==='settingsBudget'){let n=cents(t.value);if(Number.isSafeInteger(n)){state.settings.budget=n;save();renderView()}else toast('Enter a valid nonnegative budget.')}else if(t.dataset.setting){let k=t.dataset.setting;state.settings[k]=k==='contrast'?t.checked:t.value;save();applyAppearance();renderView()}}
async function restoreFile(e){let file=e.target.files?.[0];e.target.value='';if(!file)return;try{let x=JSON.parse(await file.text());if(!validImport(x))throw Error('Backup format is invalid.');if(!await ask('Replace all current data with this backup?'))return;state.settings={...structuredClone(defaults),...x.settings};state.data=Object.fromEntries(kinds.map(k=>[k,x.data[k]]));save();applyAppearance();navigate('dashboard');toast('Backup restored.')}catch(err){toast(err.message||'Could not restore backup.')}}
async function init(){try{db=await openDB();let loaded=await loadDB();if(loaded&&validImport(loaded)){state.settings={...structuredClone(defaults),...loaded.settings};state.data=Object.fromEntries(kinds.map(k=>[k,loaded.data[k]]))}else if(window.DEMO_MODE){demoSeed();save()}}catch(err){document.querySelector('#view').innerHTML='<div class="notice">Browser storage is unavailable. Check private mode or storage settings.</div>';return}if(window.DEMO_MODE)$('#demoBanner').hidden=false;applyAppearance();nav();renderView();document.addEventListener('click',handleClick);$('#editorForm').addEventListener('submit',submitForm);$('#closeEditor').addEventListener('click',closeEditor);$('#cancelEditor').addEventListener('click',closeEditor);$('#editor').addEventListener('close',()=>focusBack?.focus?.());$('#confirmNo').addEventListener('click',()=>confirmClose(false));$('#confirmYes').addEventListener('click',()=>confirmClose(true));$('#confirmDialog').addEventListener('cancel',e=>{e.preventDefault();confirmClose(false)});$('#restoreFile').addEventListener('change',restoreFile);$('#quickAdd').addEventListener('click',()=>openForm('debts'));$('#globalSearchBtn').addEventListener('click',()=>{navigate('debts');$('#listSearch')?.focus()});$('#menuBtn').addEventListener('click',()=>{let s=$('.sidebar');s.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',s.classList.contains('open'))});$('#resetDemo')?.addEventListener('click',()=>{demoSeed();save();navigate('dashboard')});document.addEventListener('change',handleChange);document.addEventListener('input',e=>{if(e.target.id!=='listSearch')return;search=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{let pos=e.target.selectionStart;let container=$('#listContainer');if(!container)return;let tmp=document.createElement('div');tmp.innerHTML=view==='debts'?debtView():view==='payments'?paymentView():genericView(view,'');let replacement=tmp.querySelector('#listContainer');if(replacement)container.replaceChildren(...replacement.childNodes)},150)})}
init();
})();
